name: backport

on:
  pull_request_target:
    types:
      - closed
      - labeled # so labels will be updated if PR is labeled after creation

jobs:
  backport:
    name: Backport PR
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'backport-to-')
    steps:
      - name: Backport Action
        uses: kwilteam/backport-github-action@b3eae3fb1be75da400e9d7094282dfcd9bc6ffa1 # kwil branch
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          auto_backport_label_prefix: backport-to-

      - name: Info log
        if: ${{ success() }}
        run: cat ~/.backport/backport.info.log

      - name: Debug log
        if: ${{ failure() }}
        run: cat ~/.backport/backport.debug.log      
